### ISSUE TITLE
Recently, I began to have difficulty with uploading files to the server. Some time server just not let me in, some time i can't list some folders, some times i can't upload files.

### ISSUE THREAD

**Issue by optimys** [WonderkidStudios/myhealthtest#23]
http://www.bugherd.com/projects/78317/tasks/24

**Comment by compass2k** [comment]
Which ftp client are you using?. I will raise a ticket with Hostek support.
This has happened before - usually when they
are moving accounts to new servers.

It usually goes away after a few days but  keep me informed.

d

**Comment by WonderkidStudios** [comment]
FileZilla

**Comment by optimys** [comment]
FileZilla

**Comment by compass2k** [comment]
Did you upgrade filezilla in the last week or recently?

Another developer upgraded a while back and found the service became
unreliable at hostek
when he rolled back the issue went away.

d

**Comment by optimys** [comment]
no

**Comment by compass2k** [comment]
Does it happen every time or intermittently?

I've opened a ticket with hostek but they can filezilla in ok and so can I
- I moved a file called test.html into the app directly a moment ago as
shown in the attached screen shot.

Is there anything else recently changed on your computer or network ?

Dan

**Comment by optimys** [comment]
Not sure what is the problem with ftp from europe - its fine from here. Anyhow I gave up on A2tech and reinstalled cpanel myself.
A look at the logs explained the fails - the new version of cpanel needs 1 gig of memory to install. I changed the rule in the install config file and its going in fine.
I have no idea why 
A2 did not check the  cpanel install and server logs but anyhow we can move on to moving across to a2 tech as soon as this has finished. I will set you a ticket when cpanel is finished. It has taken 3 hours so far.

**Comment by optimys** [comment]
please check any recent changes with your system or network as hostek and I am also not having filezilla ftp problems with compass2k.  
Anyhow cpanel should be installed soon and then we can migrate to a2tech. If your ftp doesnt work I can transfer the files.

**Comment by optimys** [comment]
Things goes much better today

**Comment by compass2k** [comment]
Strange thing when we complain to ISP support - the problem gets better
suddenly !.

Thank you for solving it we say  But they say ' we didnt do anything the
system is good must have been a glitch with you ..".

Perhaps the fairies fixed it :)

d

**Comment by optimys** [comment]
cpanel is 4 1/2 hours downloading and still working ..
