### ISSUE TITLE
migration to a2hosting / myhealthtestresults.com domain

### ISSUE THREAD

**Issue by optimys** [WonderkidStudios/myhealthtest#29]
http://www.bugherd.com/projects/78317/tasks/27

**Comment by optimys** [comment]
I have sent you cpanel credentials by email.

**Comment by optimys** [comment]
Subtasks
setup laravel in environment
duplicate db to a2 env
pull code down from repos
code repos config
bugherd install
other tasks?

**Comment by optimys** [comment]
Db clone -done
Laravel app - had beeen copied.
Mail settings - done.
Currently can't resolve ssh access settings, it just refuse connection.
(I generate ssh keys:public and private, activate it, but stel can't access)
May be problems with firewall? Need root access to whm panel or someone who maight  check firewall.
https://vpsdime.com/knowledgebase.php?action=displayarticle&id=52

**Comment by compass2k** [comment]
I asked a couple of times to for an estimate on the work before starting.
This is the model we are
trying to establish.

Perhaps you can provide this break down now.

Regarding ssh - I can get in ok but as root. Let me see what I can find out.

Did you try to setup ssh manually or through cpanel ?

d

**Comment by optimys** [comment]
Currently myhealthtestresults.com is working now, execpt bugherd widget.

**Comment by optimys** [comment]
SSH access only left.

**Comment by optimys** [comment]
That's strange but ssh has unusual port. So this is why i can't access ssh yesterday.
But it's all ok for now.

**Comment by compass2k** [comment]
So are you using your credentials or mine to get in now ?

d

**Comment by compass2k** [comment]
Using non standard protocol ports is a normal security measure to keep
random Romanians out.

d

**Comment by optimys** [comment]
I know that ssh port secure is important but i didn't expect that at new server ssh port will be changed already.
I have configured wonderkid account to work with ssh. So i may login ssh via wonderkid.

**Comment by compass2k** [comment]
There are a few odd things with ports on A2tech - they claim they dont
block its for us to firewall but they have reassigned standard ports and
they bounce some protocols too.

They never admit it until you show them a traceroute with hops terminating
just outside our server.

d
